# Generated by Django 5.2.15 on 2026-06-28 09:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/images/')),
                ('designation', models.CharField(blank=True, help_text='e.g., Consultant, Senior Consultant, Professor', max_length=255)),
                ('specialty', models.CharField(blank=True, db_index=True, help_text='e.g., Cardiology, Neurology, Orthopedics', max_length=255)),
                ('sub_specialty', models.CharField(blank=True, help_text='e.g., Interventional Cardiology', max_length=255)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('biography', models.TextField(blank=True)),
                ('primary_degree', models.CharField(blank=True, help_text='e.g., MBBS, MD, PhD', max_length=255)),
                ('additional_qualifications', models.TextField(blank=True, help_text='Additional degrees, certifications, fellowships')),
                ('current_workplace', models.CharField(blank=True, help_text='Hospital or clinic name', max_length=255)),
                ('chamber_address', models.TextField(blank=True)),
                ('consultation_time', models.CharField(blank=True, help_text='e.g., Sat-Sun: 10AM-2PM', max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('appointment_url', models.URLField(blank=True, help_text='Online appointment booking URL')),
                ('facebook_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('meta_title', models.CharField(blank=True, help_text='SEO meta title', max_length=255)),
                ('meta_description', models.TextField(blank=True, help_text='SEO meta description')),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated SEO keywords', max_length=500)),
                ('canonical_url', models.URLField(blank=True, help_text='Canonical URL for SEO')),
                ('og_title', models.CharField(blank=True, help_text='Open Graph title', max_length=255)),
                ('og_description', models.TextField(blank=True, help_text='Open Graph description')),
                ('og_image', models.ImageField(blank=True, help_text='Open Graph image', null=True, upload_to='profiles/og/')),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'doctor profile',
                'verbose_name_plural': 'doctor profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
