# Generated by Django 5.2.15 on 2026-06-29 06:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('visiting_hours', models.CharField(blank=True, help_text='e.g., Sat-Sun: 10AM-2PM', max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('serial_booking_number', models.CharField(blank=True, help_text='Phone number for booking appointments', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chambers', to='doctor.doctorprofile')),
            ],
            options={
                'verbose_name': 'Chamber',
                'verbose_name_plural': 'Chambers',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
