# Generated by Django 5.2.15 on 2026-06-29 06:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('authors', models.CharField(blank=True, help_text='Comma-separated list of authors', max_length=500)),
                ('journal_name', models.CharField(blank=True, help_text='Journal or conference name', max_length=255)),
                ('publication_type', models.CharField(choices=[('journal', 'Journal Article'), ('conference', 'Conference Paper'), ('book_chapter', 'Book Chapter'), ('thesis', 'Thesis'), ('other', 'Other')], default='journal', max_length=20)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('abstract', models.TextField(blank=True)),
                ('doi', models.URLField(blank=True, help_text='Digital Object Identifier link', verbose_name='DOI URL')),
                ('pdf_file', models.FileField(blank=True, help_text='Upload PDF of the publication', null=True, upload_to='publications/pdfs/')),
                ('external_url', models.URLField(blank=True, help_text='Link to external publication page')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='doctor.doctorprofile')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'ordering': ['display_order', '-publication_date'],
            },
        ),
    ]
