# Generated by Django 5.2.15 on 2026-06-29 06:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('youtube_url', models.URLField(help_text='Full YouTube video URL')),
                ('thumbnail', models.ImageField(blank=True, help_text='Custom thumbnail (leave blank to use YouTube default)', null=True, upload_to='videos/thumbnails/')),
                ('video_type', models.CharField(choices=[('surgery', 'Surgery'), ('educational', 'Educational'), ('interview', 'Interview'), ('other', 'Other')], default='other', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='doctor.doctorprofile')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
