# Generated by Django 5.2.15 on 2026-06-29 06:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='doctor/profile/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='doctor/cover/')),
                ('designation', models.CharField(blank=True, help_text='e.g., Consultant, Senior Consultant, Professor', max_length=255)),
                ('bmdc_number', models.CharField(blank=True, help_text='Bangladesh Medical and Dental Council registration number', max_length=50, verbose_name='BMDC Number')),
                ('qualifications', models.TextField(blank=True, help_text='List of degrees and certifications')),
                ('current_position', models.CharField(blank=True, help_text='Current job title or position', max_length=255)),
                ('workplace', models.CharField(blank=True, help_text='Hospital or clinic name', max_length=255)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('surgeries_performed', models.PositiveIntegerField(default=0)),
                ('short_biography', models.TextField(blank=True, help_text='Brief biography (2-3 paragraphs)')),
                ('full_biography_en', models.TextField(blank=True, verbose_name='Full Biography (English)')),
                ('full_biography_bn', models.TextField(blank=True, verbose_name='Full Biography (Bangla)')),
                ('facebook_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('meta_title', models.CharField(blank=True, help_text='SEO meta title', max_length=255)),
                ('meta_description', models.TextField(blank=True, help_text='SEO meta description')),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated SEO keywords', max_length=500)),
                ('canonical_url', models.URLField(blank=True, help_text='Canonical URL for SEO')),
                ('og_title', models.CharField(blank=True, help_text='Open Graph title', max_length=255)),
                ('og_description', models.TextField(blank=True, help_text='Open Graph description')),
                ('og_image', models.ImageField(blank=True, help_text='Open Graph image', null=True, upload_to='doctor/og/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Doctor Profile',
                'verbose_name_plural': 'Doctor Profile',
                'ordering': ['-created_at'],
            },
        ),
    ]
