# Generated by Django 5.2.15 on 2026-06-29 06:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blogs/images/')),
                ('excerpt', models.TextField(blank=True, help_text='Brief summary for previews and SEO')),
                ('content', models.TextField(help_text='Blog post content (supports HTML)')),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, help_text='SEO meta title', max_length=255)),
                ('meta_description', models.TextField(blank=True, help_text='SEO meta description')),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated SEO keywords', max_length=500)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='doctor.doctorprofile')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
